packageExtensions:
  "@semantic-release/commit-analyzer@*":
    peerDependencies:
      conventional-changelog-angular: "*"
  "@semantic-release/release-notes-generator@*":
    peerDependencies:
      conventional-changelog-conventionalcommits: "*"
  "@mrbernnz/semantic-release-calver@*":
    peerDependencies:
      date-fns: "*"
