name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # <--- this
      - name: Setup Node.js
        uses: oven-sh/setup-bun@v1
        with:
          cache: bun
          node-version: "lts/*"
          bun-version: 1.0.11 # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Build Assets
        run: bun run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: HUSKY=0 bun semantic-release
